# Generated by Django 3.2 on 2022-08-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
    ]
