# Generated by Django 4.1.1 on 2022-09-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_coursefeedback'),
        ('mainapp', '0005_coursefeedback'),
    ]

    operations = [
    ]
